### ISSUE TITLE
TypeScript compilation error for CommonJS modules

### ISSUE THREAD

**Issue by giancosta86** [rimbu-org/rimbu#175]
Even though the test suites in my projects referencing Rimbu (especially [Hermes](https://github.com/giancosta86/hermes) and [OmniCourse-core](https://github.com/giancosta86/OmniCourse-core)) were not affected by the changes introduced by Rimbu 1.0 and its new ESM-based packaging, alas it seems that TypeScript compilation is failing, as described by [this GitHub Actions log](https://github.com/giancosta86/hermes/actions/runs/5645388617).

As a matter of fact, this event led me to start exploring code migration to **ESM** and **vitest** as well - and I must admit that the latter seems *brilliant* indeed - but not all users might want to move to the new standard (actually, I'm facing a few issues myself - for example, I can't *compile* vitest-based tests, as described in [this still open issue](https://github.com/vitejs/vite/issues/11552)).

In the arcane world of TypeScript transpilation, I wasn't actually able to find a flag (provided it actually exists) to fix the issue caused by the new version of Rimbu - but I suspect it might be due to the fact that the library only provides ESM-compatible TypeScript declaration files, having **.d.mts** extension, in lieu of the classic **.d.ts** files with their related statements.

Needless to add that, after moving Hermes to ESM, the project compiles perfectly, and its tests run fine under vitest as well.

**Comment by vitoke** [comment]
Sorry to hear that the update broke CommonJS compatibility, I was already afraid that would be the case. Indeed I think Rimbu should be compatible, so I'll keep this on high priority. I think the main culprit is using the import/export maps internally. CommonJS has no clue how to resolve these references. In effect, I should get rid of the import maps, but export maps should still be fine.

I'm currently working on a new Rimbu package that will have a simpler structure. After publishing I'll see if I can copy that structure to all the other packages, but it will be quite a bit of work.

Thanks for bringing up the issue!

**Comment by giancosta86** [comment]
Thank you for prioritizing this issue! In the meantime, I've been facing quite a 🌊tsunami of compilation errors while trying to convert my new libraries to ESM... especially when combined with TypeScript, it still feels like an extremely experimental and fragile standard (I had serious issues with Jest + SWC, and now even with vitest, if I try to transpile my tests!) 

As for Rimbu when referenced by a CommonJS project, this line seems to provide a very interesting clue:

> Error: node_modules/@rimbu/collection-types/dist/types/main/index.d.mts(12,15): error TS2307: Cannot find module '#collection-types/map' or its corresponding type declarations.

I also agree a lot on the idea of simplifying - maybe even flattening - the directory structure within each package, because it was probably one of the main obstacles I had to deal with when extending Rimbu, whereas the code by itself was very elegant, symmetrical and clear.

I hope my hints might prove helpful! Thank you and keep up the good work!

**Comment by vitoke** [comment]
The fix has now also been released. I hope it fixes the issue, but let me know if you still run into problems.

**Comment by giancosta86** [comment]
Both projects now compile! 🥳 Thanks a lot! Keep up the 🌟excellent work!
