### ISSUE TITLE
`HashMap` "forgets" about colliding (?) keys, unlike `HashSet` 

### ISSUE THREAD

**Issue by jgreitemann** [rimbu-org/rimbu#186]
## Environment

- Rimbu version: 1.0.2 (via `deno.land/x` in Deno), 1.1.0 (via `esm.sh` in Deno, via npm in Node)
- OS: mac OS 14.1.2 (aarch64)
- runtime: Deno 1.38.3, Node 21.2.0

## Reproduction

```js
import { HashMap, HashSet } from "https://deno.land/x/rimbu@1.0.2/hashed/mod.ts";

const hs = HashSet.from([[6, 29], [2, 91]]);
console.log("Contained in set:", hs.has([6, 29]), hs.has([2, 91]));
// outputs: Contained in set: true true

const hm = HashMap.from([[[6, 29], "a"], [[2, 91], "b"]]);
console.log("Contained in map:", hm.hasKey([6, 29]), hm.hasKey([2, 91]));
// outputs: Contained in map: false false
// but I would have expected "true" on both counts.

// The specific numbers in the key arrays make a difference:
const hm2 = HashMap.from([[[6, 30], "a"], [[2, 91], "b"]]);
console.log("Contained in map:", hm2.hasKey([6, 30]), hm2.hasKey([2, 91]));
// outputs: Contained in map: true true

// But different values do not make a difference:
const hm3 = HashMap.from([[[6, 29], "c"], [[2, 91], "d"]]);
console.log("Contained in map:", hm3.hasKey([6, 29]), hm3.hasKey([2, 91]));
// outputs: Contained in map: false false
```

## Steps to reproduce

1. Save this file as `bug.js`
2. Run using `deno run bug.js`

I'm also able to reproduce using Rimbu 1.1.0 from https://esm.sh/@rimbu/hashed@1.1.0 in Deno and using the npm package in both Deno and Node.

## Expected Behavior

I would expect `HashSet.has` and `HashMap.hasKey` to behave the same. Additionally, I would not expect the presence of other entries to interfere with the result of `hasKey` for another entry.

## Actual Behavior

Behaves as indicated in the code comments. Changing any number in the array-valued keys "fixes" the problem. This suggests that these keys have colliding hashes and that the collision is not handled correctly, perhaps due to the fact that the keys are array-valued?

This problem is limited to `HashMap`, `HashSet` does not suffer from it. This again points to the fact that the keys are array-valued since the entries in the `HashMap` are also arrays. Perhaps something goes south when dealing with nested arrays?

**Comment by vitoke** [comment]
Thanks for reporting this issue. It indeed demonstrates unexpected behavior.

My quick investigation shows that it has to do with the hashing function not working properly in the HashMap. I will need some time to dive deeper into it, but I'm not sure exactly when I will get to it.

In the meantime, you can create a custom HashMap context that uses the `Hasher.anyFlatHasher()` as hashing function. For arrays this will use `.toString()` to calculate a hash, which is probably a reasonable way to hash these keys.

Here is an example:

```ts
import { HashMap, Hasher } from '@rimbu/hashed';

const CustomHashMap = HashMap.createContext({
  hasher: Hasher.anyFlatHasher(),
});

const hm = CustomHashMap.from([
  [[6, 29], 'a'],
  [[2, 91], 'b'],
]);
console.log('Contained in map:', hm.hasKey([6, 29]), hm.hasKey([2, 91]));
// outputs: Contained in map: true true
```
