### ISSUE TITLE
Why does `SortedSet` use reference equality when it removes its element?

### ISSUE THREAD

**Issue by bglgwyng** [rimbu-org/rimbu#189]
I've been using a tuple(`Array` in JS) as a key with `SortedSet.remove`.
I found that `SortedSet.remove` doesn't remove its element when it's not a primitive type.

So I investigated the implementation and found that `removeInternal` checks the reference equality before actually removing the element.
https://github.com/rimbu-org/rimbu/blob/main/packages/sorted/src/set-custom/implementation/immutable.mts#L435

Even in the case that my custom `compare` function returns `0`, the element won't be deleted.
Just commenting that line out made `remove` operate as I expected.

Is this intended behavior? Or am I missing something else?

**Comment by vitoke** [comment]
I'm pretty sure you found a genuine bug there! It should not be using reference equality, but the `context.comp` instance.
