### ISSUE TITLE
tsc 5.3 fails when using @rimbu/core in a project targeting common js output

### ISSUE THREAD

**Issue by adrian-gierakowski** [rimbu-org/rimbu#191]
as reported by this tool: https://arethetypeswrong.github.io/?p=%40rimbu%2Fcore%401.1.0

the error is:

```
error TS1479: The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported with 'require'. Consider writing a dynamic 'import("@rimbu/core")' call instead.
      To convert this file to an ECMAScript module, change its file extension to '.mts', or add the field `"type": "module"` to '/my-project/package.json'.
    
    9 import { HashMap } from '@rimbu/core'
```

applying a patch as recommended by the tool linked above fixed it

**Comment by vitoke** [comment]
Thanks, I did not know about this tool. I'll need to see with the `package.json` `exports` field, which is already quite extensive, if it is possible to specify separate types for `cjs` output. Supporting all these different modes and runtimes is becoming a science by itself 😄

**Comment by himanoa** [comment]
@vitoke Would I work on this issue?

**Comment by vitoke** [comment]
> @vitoke Would I work on this issue?

Yes it would be great if you can find a decent solution.

**Comment by himanoa** [comment]
@vitoke 
I was able to fix the problem with Masquerading as ESM, but I was not able to fix the problem with Incorrect default export.

Is it okay to make a PR in this state and make Incorrect default export a separate Pull-Request?

**Comment by vitoke** [comment]
@himanoa wow that sounds great! Sure no problem to split it into two PR's. We can keep this issue open until both PR's are merged.

**Comment by vitoke** [comment]
@himanoa I was actually thinking of removing the default exports, I'm not sure they really provide extra value. Would this make it easier?

**Comment by himanoa** [comment]
@vitoke 
> I was actually thinking of removing the default exports, I'm not sure they really provide extra value. Would this make it easier?

I feel like that's needed to fix the Incorrect default exports issue.

I feel that it is better to delete the menu subpackage. Because the exports field in package.json is not interpreted uniformly by bundlers, so it is easy to break if you create a complexity exports definition/
