### ISSUE TITLE
ifExists function for MultiMap throws error

### ISSUE THREAD

**Issue by st-clair-clarke** [rimbu-org/rimbu#95]
## Environment
OS: Linux Cinnamon
Node: v16.13.0
Google Chrome Version 105.0.5195.102 (Official Build) (64-bit)

## Reproduction
I am following the example at [https://rimbu.org/api/rimbu/multimap/MultiMap/interface](https://rimbu.org/api/rimbu/multimap/MultiMap/interface) an dexperimenting.

I reproduce all examples up the modfyAt() function usage. The following example that uses the ifExists function does not compiles, with the error

```
const m = HashMultiMapHashValue.of([1, 'a'], [2, 'b'])
console.log(m.modifyAt(2, { ifExists: ['c'] }).toArray())
```

## Steps to reproduce

const m = HashMultiMapHashValue.of([1, 'a'], [2, 'b'])
console.log(m.modifyAt(2, { ifExists: ['c'] }).toArray())

## Expected Behavior

console output |  [[1, 'a'], [2, 'c']]

## Actual Behavior

Error: symptom-detail-history.component.ts:95:33 - error TS2322: Type 'string[]' is not assignable to type '(currentValues: NonEmpty<string>) => StreamSource<string>'.
  Type 'string[]' provides no match for the signature '(currentValues: NonEmpty<string>): StreamSource<string>'.

95     console.log(m.modifyAt(2, { ifExists: ['c'] }).toArray())
                                   ~~~~~~~~

  node_modules/.pnpm/@rimbu+multimap@0.9.19/node_modules/@rimbu/multimap/dist/types/custom/interface/base.d.ts:411:9
    411         ifExists?: (currentValues: WithKeyValue<Tp, K, V>['keyMapValuesNonEmpty']) => StreamSource<V>;
                ~~~~~~~~
    The expected type comes from property 'ifExists' which is declared here on type '{ ifNew?: OptLazy<StreamSource<string>>; ifExists?: (currentValues: NonEmpty<string>) => StreamSource<string>; }'

✖ Failed to compile.
-->

**Comment by vitoke** [comment]
Thanks for the detailed report! Indeed the example is incorrect, the `ifExist` option currently only receives a function that returns a new value. I will fix the examples.
However, I have also created a [New Issue] to investigate whether it would be possible for it to also receive direct new values.
